name: Trigger auto deployment for tatva-frontpmsusers-evalus

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/tatva-frontpmsusers-evalus-AutoDeployTrigger-793c4fc9-1c66-43c3-ab4d-c52824924e4e.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.TATVAFRONTPMSUSERSEVALUS_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.TATVAFRONTPMSUSERSEVALUS_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.TATVAFRONTPMSUSERSEVALUS_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: userloginservice.azurecr.io
          registryUsername: ${{ secrets.TATVAFRONTPMSUSERSEVALUS_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.TATVAFRONTPMSUSERSEVALUS_REGISTRY_PASSWORD }}
          containerAppName: tatva-frontpmsusers-evalus
          resourceGroup: tatva-prod
          imageToBuild: userloginservice.azurecr.io/tatva-frontpmsusers-evalus:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


